# -*- coding: utf-8 -*-
"""internship-app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb2onYfJcNO31mlBcLjyywz6nMFaxyv1
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix, hstack
import ast
import re
import pickle
import os

app = Flask(__name__)
CORS(app)

df = None
tfidf = None
locationtfidf = None
scaler = None
final_features = None

def flatten_list_text(x):
    if pd.isna(x):
        return ""
    try:
        val = ast.literal_eval(x)
        if isinstance(val, (list, tuple)):
            return " ".join(val)
    except:
        return str(x)

def cleanLocation(x):
    if pd.isna(x) or str(x) == 'nan':
        return "Work from home"
    x = re.sub(r"[()'\\[\\]]", "", str(x))
    x = re.sub(r"\\s*,\\s*", " ", x)
    return x.strip().rstrip(',').strip()

def cleanDuration(x):
    if pd.isna(x):
        return np.nan
    x = x.strip().lower()
    num = int(x.split()[0])
    unit = x.split()[1]
    if "week" in unit:
        return num * 0.25
    elif "month" in unit:
        return num * 1.0
    else:
        return np.nan

def cleanStipend(x):
    if pd.isna(x) or "unpaid" in str(x.lower()):
        return np.nan, np.nan, np.nan
    x = re.sub(r"[₹,]", "", x)
    x = re.sub(r"[^0-9\\-]", "", x)
    if '-' in x:
        parts = x.split('-')
        if len(parts) == 2:
            low, high = int(parts[0]), int(parts[1])
            return low, high, (int(low) + int(high)) / 2
    else:
        val = int(x) if x else np.nan
        return val, val, val

def load_and_preprocess_data():
    global df, tfidf, locationtfidf, scaler, final_features

    # Load dataset
    df = pd.read_csv("internship_data.csv")

    # Preprocess text features
    df["Role_text"] = df["Role"].astype(str)
    df["Skills_text"] = df["Skills"].apply(flatten_list_text)
    df["Combined_text"] = df["Skills_text"] + " " + df["Role_text"]

    # TF-IDF for skills + role
    tfidf = TfidfVectorizer(max_features=2000, ngram_range=(1, 3), stop_words='english')
    text_features = tfidf.fit_transform(df["Combined_text"])

    # Process location
    df["Location"] = df["Location"].astype(str)
    df["Location_clean"] = df["Location"].apply(cleanLocation)
    locationtfidf = TfidfVectorizer(max_features=200, ngram_range=(1, 2), stop_words=None)
    location_features = locationtfidf.fit_transform(df["Location_clean"])

    # Process duration and stipend
    df["Duration_clean"] = df["Duration"].apply(cleanDuration)
    stipend_data = df['Stipend'].apply(cleanStipend)
    df[['Stipend_min', 'Stipend_max', 'Stipend_avg']] = pd.DataFrame(stipend_data.tolist())

    df['Duration_months'] = df['Duration_clean'].copy()
    df['Stipend_rupees'] = df['Stipend_avg'].copy()

    # Scale numeric features
    numeric_cols = ['Duration_clean', 'Stipend_avg']
    scaler = MinMaxScaler()
    df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

    # Create final feature matrix
    numeric_features = df[["Duration_clean", "Stipend_avg"]].fillna(0).values
    numeric_csr = csr_matrix(numeric_features)

    final_features = hstack([
        text_features * 0.7,
        location_features * 0.2,
        numeric_csr * 0.1
    ])

    print("Model loaded and preprocessed successfully!")

def recommend_internships(user_skills, user_location="", preferred_duration=None,
                          preferred_stipend=None, top_k=1):
    user_text_vec = tfidf.transform([user_skills])
    user_location_vec = locationtfidf.transform([user_location if user_location else "Work from home"])

    if preferred_duration is None:
        preferred_duration = df["Duration_months"].median()
    if preferred_stipend is None:
        preferred_stipend = df["Stipend_rupees"].median()

    user_numeric = np.array([[preferred_duration, preferred_stipend]])
    user_numeric_scaled = scaler.transform(user_numeric)
    user_numeric_vec = csr_matrix(user_numeric_scaled)

    user_features = hstack([user_text_vec * 0.7,
                            user_location_vec * 0.2,
                            user_numeric_vec * 0.1])
    similarities = cosine_similarity(user_features, final_features).flatten()

    top_indices = similarities.argsort()[-top_k:][::-1]

    results = df.iloc[top_indices][[
        'Role', 'Company Name', 'Location_clean',
        'Stipend', 'Duration', 'Skills_text'
    ]].copy()

    results['Match_Score'] = similarities[top_indices]
    results['Match_Percentage'] = (similarities[top_indices] * 100).round(2)

    return results.to_dict('records')

@app.route('/api/recommend', methods=['POST'])
def get_recommendations():
    try:
        data = request.json

        user_skills = data.get('skills', '')
        user_location = data.get('location', '')
        preferred_duration = data.get('duration', None)
        preferred_stipend = data.get('stipend', None)
        top_k = 1

        if not user_skills:
            return jsonify({'error': 'Skills are required'}), 400

        recommendations = recommend_internships(
            user_skills=user_skills,
            user_location=user_location,
            preferred_duration=preferred_duration,
            preferred_stipend=preferred_stipend,
            top_k=top_k
        )

        return jsonify({
            'success': True,
            'allocation': recommendations[0] if recommendations else None
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/health', methods=['GET'])
def health_check():
    return jsonify({'status': 'healthy'})

if __name__ == '__main__':
    # Load data on startup
    load_and_preprocess_data()
    app.run(debug=True, port=5000)